lilyinstarlight/nixos-cosmic

flake.lock, nixos/cosmic/module.nix
Hello, and thank you for this repo!
Without changing anything beyond a `nix flake update`, today I got this while trying to rebuild:
```
error: The option `services.xserver.displayManager.sessionPackages' does not exist. Definition values:
- In `/nix/store/z0pdqcm1ywkha41a95khs6qa3bwr3yki-source/nixos/cosmic/module.nix':
{
_type = "if";
condition = true;
content = [
<derivation cosmic-session-0-unstable-2024-04-08>
...
```
per [this discussion](https://github.com/NixOS/nixpkgs/pull/291913#issuecomment-2046586711) and [commit](https://github.com/NixOS/nixpkgs/commit/476b8c276e2ae4c98efd1d8d759029e170c5ca98) it appears the correct syntax is now without xserver, much as the cosmic module itself uses desktopManager/displayManager without xserver prefix.
I assume most people using this will be …
=> remove 'xserver' prefix from displayManager.sessionPackages

nixos/cosmic-greeter/module.nix, nixos/cosmic/module.nix
hello, another very useful PR to remove a nix warning :)
=> nixos/cosmic: remove 'xserver' prefix from libinput

nixos/cosmic/module.nix
This PR adds Gnome Keyring according to this [discussion](https://www.reddit.com/r/pop_os/comments/1cvd3u9/cosmic_de_which_keyring_to_use/).
This is unable to manage ssh-keys yet, see: https://github.com/NixOS/nixpkgs/pull/310978
=> nixos/cosmic: add gnome-keyring

.github/workflows/ci_aarch64.yml, .github/workflows/cosmic.yml, .github/workflows/flake.yml
Add a workflow for building COSMIC derivations on an AArch64 runner.
The GitHub App https://github.com/apps/drakon64-github-actions-runner-aws has to be added to the repository before running the workflow so that the webhook that creates the runner instance is enabled.
The specs of the instance are as follows:
- CPU: 2 vCPU's (AWS Graviton3)
- Given that build parallelism is disabled in the existing workflows I assumed 4 vCPU's (the same as a GitHub-hosted runner) would be redundant, but I can make this change if need be
- Memory: 16 GiB (same as a GitHub-hosted runner)
- Storage: 14 GB SSD (same as a GitHub-hosted runner)
We could potentially increase build parallelism if we increase the size of the runner instance, I'm happy to have that discussion.
I'm willing to host this until COSMIC …
=> CI: Build for AArch64

.github/workflows/ci.yml
The disk size on the AArch64 build runner was temporarily increased to 30GB for all repositories. As the disk size can now be configured as part of a workflow, this PR explicitly sets the disk size to the required 30GB so that builds will be unaffected when I eventually return the default back to its original 14GB.
=> AArch64 CI: Increase disk size to 30GB

.github/workflows/ci.yml
I noticed when attempting to build for AArch64 that the build exceeds the default GitHub Actions timeout of six hours. Looking at the runs here, it wasn't an AArch64-exclusive issue.
This does require running x86_64 builds on a self-hosted runner as GitHub does not allow jobs to run longer than six hours on their runners.
=> CI: Increase job timeout to one day

readme.md
Given that we now have a build cache for AArch64 (and far as I'm aware NixOS doesn't support any other architectures), the note about the build cache being x86_64-only can be removed.
=> Readme: Remove cache information about non-x86_64 architectures

.github/mergify.yml, .github/workflows/ci.yml, flake.lock, flake.nix
Builds and caches for nixos-24.05 as well as nixos-unstable
@drakon64 Is doing two builds per architecture per CI run going to be okay for the AWS builders? (especially in terms of cost)
Fixes #139
=> ci: use build matrix for building and caching stable packages as well

pkgs/cosmic-greeter/package.nix
Current `cosmic-greeter` builds are failing due to a dependency on `libudev` and `libinput`. This PR resolves the dependency.
=> Add `udev` and `libinput` to `cosmic-greeter` build inputs

.github/workflows/ci.yml
Increase the cores available to Nix builds to 2.
Compared to the current setting of 1, this can potentially reduce a 6.5 hour build to a 4.5 hour build, see https://github.com/drakon64/nixos-cosmic/actions/runs/9487855050 where all caches were disabled. Interestingly, ARM builds are also faster than x86 as a result.
This does lead to swap being used but I do not believe we are at risk of resource exhaustion.
=> CI: Increase cores to 2

.github/workflows/ci.yml
Remove the custom timeout for CI builds and return to the default. There's two reasons for doing this:
1. https://github.com/lilyinstarlight/nixos-cosmic/pull/165 made a custom timeout redundant
2. Builds are currently being help up because of an issue with starting the ARM runners. When an ARM runner is requested, the previous job that was being held up ends up running on the new runner and then the new job is then held up. I'm working on fixing the source of this issue.
This will likely cause the next CI build to fail due to a timeout (because of point 2) but the build after should return to normal.
=> CI: Remove custom timeout

readme.md
Mention in the README file that NixOS 24.05 is supported and that a binary cache is available
=> Readme: Clarify NixOS 24.05 support

nixos/cosmic/module.nix
A workaround that allows Cosmic DE to be enabled together with one of the following DEs:
- Gnome
- Deepin
- Cinnamon
- Phosh
Fixes #17
=> Workaround for conflicting xdg-desktop-portal-gtk

readme.md
I wanted to try Cosmic and ended up here after googling my way to the tracking issue. 
Thanks for taking the time to make this flake!
I thought this readme could lead back to the tracking issue for people to easily find what is going on and test Cosmic on NixOS. 
Same for the matrix room.
=> readme: link tracking issue and matrix room

.github/workflows/ci.yml
I've moved the AWS instances from London to Frankfurt which gives us a few more instance options.
In summary:
- x86_64: Intel Xeon Scalable 8488C -> AMD EPYC 9R14
- Higher clock speed
- No SMT
- vCPU count remains the same
- AArch64: AWS Graviton3 -> AWS Graviton4
- Generational upgrade
Phoronix has some benchmarks comparing the old to the new but in a larger vCPU/memory configuration https://www.phoronix.com/review/aws-graviton4-benchmarks/4
=> CI: Upgrade runner instance types

.github/workflows/ci.yml
I've been running some tests to reduce build times. For whatever reason the Rust compiler isn't able to fully utilise 16 cores, so it seems like 8 cores is the next best option that doesn't lead to underutilisation.
In testing, this reduced the x86_64 Unstable build time to {{ time }} (my last test was with 16 cores, haven't had the time to test with 8 cores yet).
Draft as the `EBS-Swap` option is currently not merged into the main CI Lambda function, but I think it would still be good to get comments on this.
=> CI: increase core count, memory, and swap

nixos/cosmic/module.nix
Cosmic uses playerctl to implement the XF86 Media keys, see pop-os/cosmic-settings-daemon#41
=> nixos/cosmic: Add playerctl as a dependency

pkgs/cosmic-settings/package.nix
Spotted this when trying to diagnose an `icu_datetime` build issue (which I couldn't replicate).
This is needed for the COSMIC pipeline to run. There's still an issue where pkg-config isn't finding `libclang`, not sure how to fix that one.
=> Add `pipewire` to `cosmic-settings` build inputs

.github/workflows/ci.yml
As part of https://github.com/lilyinstarlight/nixos-cosmic/pull/246 the CI instances were given significantly more cores and memory. It turns out that the memory upgrades weren't necessary, so this PR reduces the memory allocated to the x86_64 instance while keeping the core count the same.
We currently cannot do this for AArch64 without also downgrading the CPU generation. Given that AArch64 builds currently lag behind x86_64, I don't want to make this worse.
=> CI: Reduce memory for x86_64

pkgs/cosmic-bg/package.nix
Currently the COSMIC workflow is failing because https://github.com/pop-os/cosmic-bg/commit/ed9ea6cc15638b08c848fda042ec2df3ff69865f#r145966372 has been addressed and the `postFetch` stage of pulling the source code for `cosmic-bg` fails because the fix is no longer needed and no longer works.
This change bumps `cosmic-bg` to a version where this fix is no longer required and removes the fix.
=> Remove workaround for cosmic-bg Cargo dependency

pkgs/cosmic-greeter/package.nix, pkgs/cosmic-settings/package.nix
The xkb-data crate used hard-coded paths for locating the xkb rule XML files. Since version 0.2.1 there is a way to overwrite these hard-coded paths using the X11_BASE_RULES_XML and X11_EXTRA_RULES_XML environment variables. This patch adds these variables to the wrappers of cosmic-settings and comsic-greeter.
This should fix issue #74 for cosmic-settings. cosmic-greeter should start working as soon as the cosmic devs bump its version of the xkb-data crate.
=> add env variables for xkb-data paths

.github/workflows/ci.yml
This brings the AArch64 CI instance in line with the x86_64 instance. The CPU is unchanged, there's just less memory now (which wasn't being used anyway).
Finishes the work started in https://github.com/lilyinstarlight/nixos-cosmic/pull/266.
=> CI: Reduce memory for AArch64

nixos/cosmic/module.nix
per [this issue/comment](https://github.com/pop-os/cosmic-epoch/issues/1069#issuecomment-2397624433), COSMIC Session requires the cosmic-files package to provide desktop context menus, and will refuse to launch without it.
this PR detects if cosmic-files is in the excludedPackages list and informs the user of potential consequences.
=> nixos/cosmic: add warning if cosmic-files is excluded

.github/workflows/ci.yml
Temporarily replace the existing CI solution with two long-running VM's (one for x86-64 and one for AArch64). These VM's have less resources allocated to them than the usual CI, so Nix has to be told to run on less cores (to be honest I'm not sure throwing 8 CPU's at Nix was efficient given how the Cargo wrapper works).
=> Temporarily replace the existing CI

.github/workflows/ci.yml
Temporarily increase build time limit to 12 hours until we have faster build runners
=> Temporarily increase build time limit

.github/workflows/ci.yml
Setting this will force Nix to collect garbage when the partition where `/nix` is stored reaches less than 1 GB of free space.
=> Set `min-free` to prevent CI disk filling up

.github/workflows/ci.yml
Return to using ephemeral self-hosted runners rather than leaving two runners on 24/7.
As these runners are only on while a build is running, we can make them larger. My account currently has a quota for CPU cores so I've had to allocate 4 cores rather than the desired 8, but I'm hoping to get this resolved.
The x86 VM is an Intel Sapphire Rapids, and the AArch64 VM is a Google Axion. Both have 4 cores and 32 GiB memory.
=> CI: Use ephemeral self-hosted runners (again)

pkgs/cosmic-session/package.nix
Fixes #517 by setting correct dconf profile location.
=> cosmic-session: add variable for dconf profile location

.github/workflows/ci.yml
Issues with self-hosted runner registration are still being looked into, but VM type doesn't seem to be the cause. This also prevents builds being held up on waiting for the VM type to be available.
=> Revert changes to stable/unstable CI VM's

.github/workflows/ci.yml
My request for additional CPU quota was approved for x86, so we can now use the same shape for x86 builds.
Unfortunately the same request was rejected for ARM, ~~so the ugly hack has to stay for now~~.
=> Use the same VM shape for all x86 builds

pkgs/cosmic-ext-tweaks/package.nix, pkgs/cosmic-store/package.nix, pkgs/examine/package.nix, pkgs/forecast/package.nix, pkgs/stellarshot/package.nix, pkgs/tasks/package.nix
These environment variables were not necessary anymore, since vergen is not being used anymore in the About page of these applications.
Eventually the vergen hook could also be dropped from libcosmicAppHook, after all cosmic applications are updated to an updated version of libcosmic
=> treewide: remove unnecessary vergen env variables

pkgs/cosmic-session/package.nix
This fixes issues with portal that were happening after c1ddac0.
=> cosmic-session: update substitution pattern for start-cosmic script

pkgs/cosmic-files/package.nix
Checks are not failing anymore. Using regular `cargoTestFlags`  because it shouldn't really matter like it does for the `buildPhase`
=> cosmic-files: re-enable checks

nixos/cosmic-greeter/module.nix, nixos/cosmic/module.nix
Adds a package option for cosmic-greeter, also updates cosmic module to use `services.displayManager.cosmic-greeter.package` for the cosmic-greeter package
=> nixos/cosmic-greeter: add package option

flake.lock, flake.nix
Required due to COSMIC now requiring Rust 1.84 at the minimum and NixOS 24.11 packaging Rust 1.83.
This is effectively a revert of c91f1104f886f9b3211fca2570931c50f69443f4 but also bumps the minimum required Rust version to 1.84, so this should only apply to NixOS 24.11 builds and not Unstable.
=> Re-enable the Rust overlay

pkgs/cosmic-greeter/package.nix
Cosmic greeter now uses vergen and needs the variable to build successfully.
=> cosmic-greeter: Add VERGEN_GIT_SHA variable
